// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_ControleALunos.Data;

namespace Projeto_ControleALunos.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230306003420_BancNovo2")]
    partial class BancNovo2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_ControleALunos.Models.AlunosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.DisciplinasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatriculasId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matriculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatriculasId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.MateriasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MateriasModel");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.MatriculasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunosId")
                        .HasColumnType("int")
                        .HasColumnName("AlunosId");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("MateriasId")
                        .HasColumnType("int")
                        .HasColumnName("MateriasId");

                    b.HasKey("Id");

                    b.HasIndex("AlunosId");

                    b.HasIndex("MateriasId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.NotasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNota")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriasId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunosId");

                    b.HasIndex("MateriasId");

                    b.ToTable("NotasModel");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.DisciplinasModel", b =>
                {
                    b.HasOne("Projeto_ControleALunos.Models.MatriculasModel", "Matriculas")
                        .WithMany("Disciplinas")
                        .HasForeignKey("MatriculasId");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.MatriculasModel", b =>
                {
                    b.HasOne("Projeto_ControleALunos.Models.AlunosModel", "Alunos")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_ControleALunos.Models.MateriasModel", "Materias")
                        .WithMany("Matriculas")
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.NotasModel", b =>
                {
                    b.HasOne("Projeto_ControleALunos.Models.AlunosModel", "Alunos")
                        .WithMany("Notas")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_ControleALunos.Models.MateriasModel", "Materias")
                        .WithMany("Notas")
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.AlunosModel", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.MateriasModel", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Projeto_ControleALunos.Models.MatriculasModel", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
